[tool.poetry]
name = "won"
version = "0.0.4"
description = ""
authors = ["Mariusz Kabala <mariusz@kabala.waw.pl>"]

[tool.poetry.dependencies]
python = "^3.7"
wakeonlan = "*"
paho-mqtt = "^1.5.0"
python-json-logger = "^0.1.11"
flask = "*"
requests = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[package]
include = ["*.py"]
