---
    - hosts: homeSrv2
    
      vars:
        - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        - homeDir: /home/pi
        - project_path: /opt/pytomation/{{ app }}
        - repo: homeAutomationPy
        - account: mariusz-kabala
        - privateKey: ~/.ssh/id_rsa
    
      tasks:
        - name: Set variables
          set_fact:
            release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
            current_path: "{{ project_path }}/current"
            local_copy_path: "~/{{ repo }}"
            supervisor_config_path: "homeAutomation_{{ app }}.conf"
    
        - name: Clone the repository
          local_action: git repo="git@github.com:{{account}}/{{repo}}.git" dest={{local_copy_path}}
    
        - name: Retrieve current release folder
          command: readlink -f current
          register: current_release_path
          ignore_errors: yes
          args:
            chdir: "{{ project_path }}"
          
        - name: Create new folder
          file:
            dest={{ release_path }}
            mode=0755
            recurse=yes
            state=directory
    
        - name: Copy application code to remote
          copy: src={{local_copy_path}}/packages/{{app}}/ dest={{release_path}} mode=0600
    
        - name: Copy supervisor config to remote
          become: yes
          copy: src={{local_copy_path}}/deploy/supervisor/{{ supervisor_config_path }} dest=/etc/supervisor/conf.d/{{ supervisor_config_path }}
    
        - name: restore dependencies via pipenv
          command: pipenv install
          args:
            chdir: "{{ release_path }}"
    
        - name: Update symlink
          file:
            src={{ release_path }}
            dest={{ current_path }}
            state=link
        
        - name: Restart the app
          become: yes
          supervisorctl:
            name: homeAutomation-{{app}}
            state: restarted
            config: /etc/supervisor/conf.d/{{ supervisor_config_path }}
      