[tool.poetry]
name = "lgtv"
version = "0.1.0"
description = ""
authors = ["Mariusz Kabała <mariusz@kabala.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pywebostv = "^0.8.8"

[tool.poetry.scripts]
start = 'lgtv:start'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
