[tool.poetry]
name = "lgsoundbar"
version = "0.1.0"
description = ""
authors = ["Mariusz Kabała <mariusz@kabala.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
temescal = "^0.5"
tornado = "^6.2"

[tool.poetry.scripts]
start = 'lgsoundbar:start'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
